### ISSUE TITLE
adnilg issues

### ISSUE THREAD

**Issue by justinbmeyer** [justinbmeyer/jbm#2]
P0

- [x] [Broken Update Request Form](https://github.com/justinbmeyer/jbm/issues/2#issuecomment-404937473) - fixed
- [x] [Broken Schedule Request Link](https://github.com/justinbmeyer/jbm/issues/2#issuecomment-404938294) - fixed
- [x] [Verify All doesn't seem to work](https://github.com/justinbmeyer/jbm/issues/2#issuecomment-404944607) - fixed

P1 

- [x] [broken external link](#issuecomment-404936874) - they aren't broken, they're just strange. The URL is an encoded version of something like `/icloud/production/deployments/<a class="link-mleft" target="_blank" onclick='window.open("http://localhost:3030/glinda/tasks/56079/view/health.carnival?name=condor&filterType=correct");return false;'>undefined</a>`
- [x] [verifying doesn't seem to work](https://github.com/justinbmeyer/jbm/issues/2#issuecomment-404941930)
- [x] [Creating a freeze doesn't work](https://github.com/justinbmeyer/jbm/issues/2#issuecomment-404948525) - this is broken on UAT also
- [x] [Property Differential doesn't seem to work](https://github.com/justinbmeyer/jbm/issues/2#issuecomment-404950745) - this is working for me... they're just autocomplete inputs so you have to know what to type.
- [x] [Executive Overview Filter Form doesn't seem to work](https://github.com/justinbmeyer/jbm/issues/2#issuecomment-404952933) - Although it looks like one, this isn't a filter. It's just the overall status of the deployment.

**Comment by justinbmeyer** [comment]
Clicking:

![image](https://user-images.githubusercontent.com/78602/42710092-4ce095e2-86a8-11e8-940b-dae017b66b62.png)


shows:

![image](https://user-images.githubusercontent.com/78602/42710099-558f5854-86a8-11e8-89e3-819f1084b9ab.png)

**Comment by justinbmeyer** [comment]
__P5__

Double scrollbar:

![image](https://user-images.githubusercontent.com/78602/42710951-cb004afa-86ab-11e8-8685-da46c883472f.png)

**Comment by justinbmeyer** [comment]
__P4__

I assume you click the whole menu, but I thought maybe you should be able to click the numbers?

![recording-50](https://user-images.githubusercontent.com/78602/42711020-0955d874-86ac-11e8-9907-7464baba4844.gif)

**Comment by justinbmeyer** [comment]
__P1__

These links seem to open up to broken urls:

![image](https://user-images.githubusercontent.com/78602/42711167-83b018be-86ac-11e8-89b0-20ec3b2629ac.png)

Clicking around opened:

```
https://smart-starfish-5.localtunnel.me/?icloud%2Fproduction%2Fdeployments%2F%3Ca+class=%22link-mleft%22+target%3D%22_blank%22+onclick%3D%27window.open(%22https%3A%2F%2Fsmart-starfish-5.localtunnel.me%2Fglinda%2Ftasks%2F56115%2Fview%2Fhealth.carnival%3Fname%3Dcondor&filterType=correct%22)%3Breturn+false%3B%27%3Eundefined%3C%2Fa%3E
```

**Comment by justinbmeyer** [comment]
__P5__

Popup cut off:

![image](https://user-images.githubusercontent.com/78602/42711225-ac5ec3fa-86ac-11e8-8d44-3b6602f289ed.png)

**Comment by justinbmeyer** [comment]
__P0__

Clicking:

![image](https://user-images.githubusercontent.com/78602/42711321-0a1db76c-86ad-11e8-9a58-1869f2bd5e99.png)


![image](https://user-images.githubusercontent.com/78602/42711291-e7a08700-86ac-11e8-88cf-5da394c68368.png)


Then trying to submit: 

![image](https://user-images.githubusercontent.com/78602/42711269-d6233428-86ac-11e8-947f-7098e9033d60.png)

**Comment by justinbmeyer** [comment]
__P3__

How do you make these verifications change?

![image](https://user-images.githubusercontent.com/78602/42711358-2f9b5e54-86ad-11e8-9b88-b7601221d7c3.png)

Nothing I do seems to change them.  Is this a bug?

**Comment by justinbmeyer** [comment]
__P0__

Another broken event handler:

![image](https://user-images.githubusercontent.com/78602/42711409-5d9c2d1a-86ad-11e8-81a2-ca33b3300694.png)

**Comment by justinbmeyer** [comment]
__P2__

These seem like links but do nothing on click:

![image](https://user-images.githubusercontent.com/78602/42711489-ab9caf26-86ad-11e8-8df2-02c845f16fd5.png)

**Comment by justinbmeyer** [comment]
__P1__

Verifying doesn't seem to work: 

![image](https://user-images.githubusercontent.com/78602/42711995-92e6602e-86af-11e8-9fc6-022886d072bb.png)


I'm not sure if this is a bug or not.  A lot of errors about not being able to find the key `id`.

**Comment by justinbmeyer** [comment]
__P2__

I'm seeing a set warning:

```
dev-bundle.js:3 One or more items were retrieved which do not match the 'Set' parameters used to load them. Read the docs for more information: https://canjs.com/doc/can-set.html#SolvingCommonIssues

Below are the 'Set' parameters:
{
  "active": true,
  "nullApplications": true
}

And below is an item which does not match those parameters:
{
  "id": 6,
  "active": true,
  "start": "2018-01-04T18:00:00.000Z",
  "end": "2018-01-05T20:30:00.000Z",
  "message": "Executive demos, Thu 1/4 10am - Fri 1/5 12:30pm",
  "user": "Ron Labao",
  "application": null,
  "platform": null,
  "createdAt": "2018-01-04T18:20:55.675Z",
  "updatedAt": "2018-01-04T18:20:55.675Z",
  "environmentId": 5,
  "environment": {
    "codeName": "icloud3",
    "name": "iCloud3"
  }
}
```

**Comment by justinbmeyer** [comment]
__P0__

Verify All doesn't work:

![image](https://user-images.githubusercontent.com/78602/42712415-3455d65a-86b1-11e8-9ce3-0c21f8bb3edc.png)

**Comment by justinbmeyer** [comment]
__P2__


Search doesn't seem to work:

![image](https://user-images.githubusercontent.com/78602/42712578-d1e7a88a-86b1-11e8-8232-3048124aa4cf.png)

**Comment by justinbmeyer** [comment]
__P3__

This might be a UI bug, but after you click `Create Requests` it the button stays the same, making it more likely someone will keep clicking it:

![image](https://user-images.githubusercontent.com/78602/42712752-6eb6a40e-86b2-11e8-87f8-afed7ff45952.png)

**Comment by justinbmeyer** [comment]
__P5__

Another minor bit of UI weirdness:

![image](https://user-images.githubusercontent.com/78602/42712782-9320cf68-86b2-11e8-8bc0-ae997a696e80.png)


There is a lot of space between the checkbox and content.  I wouldn't have noticed if the horizontal space on my monitor wasn't so large.

**Comment by justinbmeyer** [comment]
__P1__

Creating a freeze didn't seem to work:

![image](https://user-images.githubusercontent.com/78602/42713005-7209232e-86b3-11e8-947f-fa1a862388e9.png)

Nothing appeared in the list.

**Comment by justinbmeyer** [comment]
__P4__

This is probably a UI bug, but if you click on 10, you can't see pages to the right of it:

![image](https://user-images.githubusercontent.com/78602/42713140-07c9e4f2-86b4-11e8-9544-606dda717131.png)

**Comment by justinbmeyer** [comment]
__P1__

![image](https://user-images.githubusercontent.com/78602/42713315-a6789076-86b4-11e8-9245-9f320e369a9a.png)


This is likely due to the slow internet connection, but the "refresh" icon stays visible for a long time, then goes away:

![image](https://user-images.githubusercontent.com/78602/42713247-6852a822-86b4-11e8-83e6-0ee01f2bada8.png)

After it goes away, I can type in the input:

![image](https://user-images.githubusercontent.com/78602/42713277-7df97bb0-86b4-11e8-95e3-58b0913b4a1b.png)

But this seems odd / wrong?

I think this form is broken, I'm unable to make the `Find Differential` button activate:

![image](https://user-images.githubusercontent.com/78602/42713344-c3d6a220-86b4-11e8-8028-43f472c0140c.png)

**Comment by justinbmeyer** [comment]
__P5__

Probably a UI bug, but hovering over the column, just below the column text, shows a cursor pointer.

![image](https://user-images.githubusercontent.com/78602/42713514-5a329c6a-86b5-11e8-9907-adfaa728b2c0.png)

**Comment by justinbmeyer** [comment]
__P1__

Changing the form doesn't seem to change the content below:

![image](https://user-images.githubusercontent.com/78602/42713669-e251ecb8-86b5-11e8-8435-8306a6b2b1a8.png)

**Comment by justinbmeyer** [comment]
__P2__

Creating a deployment warns about a key:

![image](https://user-images.githubusercontent.com/78602/42713790-4dad75e0-86b6-11e8-86f6-7b561c79520d.png)

This sort of warning usually means a bug.

**Comment by phillipskevin** [comment]
The P0s and P1s have been fixed and QA is regression testing now so I'm going to close this.
